baseURL = "https://hanivan.github.io/blog"
languageCode = "en-us"
title = "Nip's Journey"
theme = "smol"

# Parameters
[params]
    subtitle = "Indonesia"
    dateFmt = "Monday, Jan 2, 2006 04:15"

# Taxonomies
[taxonomies]
  tag = "tags"
  
# Highlighter
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    pygmentsUseClasses=true
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 2

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = ""
        weight = 1

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "tags"
        weight = 2

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/Hanivan"
        weight = 1

    [[menu.footer]]
        name = "Youtube"
        url = "https://youtube.com/lintasanvideo"
        weight = 2

    [[menu.footer]]
        name = "Instagram"
        url = "https://instagram.com/hanivanrizky"
        weight = 3
