baseURL = "https://hanivan.github.io/blog"
languageCode = "en-us"
title = "Nip's Journey"
theme = "smol"
summaryLength = 25
paginate = 7

# Parameters
[params]
    description = "Menulis semaunya"
    subtitle = "Indonesia"
    dateFmt = "Monday, 2006-01-02"

# Taxonomies
[taxonomies]
  tag = "tags"
  
# Highlighter
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    pygmentsUseClasses=true
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 2

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = ""
        weight = 1

[[menu.main]]
        identifier = "modules"
        name = "Modules"
        url = "modules"
        weight = 2

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "tags"
        weight = 3

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/Hanivan"
        weight = 1

    [[menu.footer]]
        name = "Youtube"
        url = "https://youtube.com/lintasanvideo"
        weight = 2

    [[menu.footer]]
        name = "Instagram"
        url = "https://instagram.com/hanivanrizky"
        weight = 3

[[menu.footer]]
        name = "Donasi^o^"
        url = "https://saweria.co/hanivanrizky"
        weight = 4
